### ISSUE TITLE
Support for an empty content?

### ISSUE THREAD

**Issue by jperry** [chef-cookbooks/ohai#18]
Right now if you don't supply a content the .json file isn't created.  Is this intentional?  For now I have to put some garbage key in my content for an ec2.json to be created since vpc instances aren't detected automatically.

**Comment by toddmichael** [comment]
Ran into this one this evening as well.  Glad I saw this before I finished yanking ALL my hair out.

**Comment by jmauro** [comment]
Patch given into https://github.com/opscode-cookbooks/ohai/pull/22

**Comment by lmickh** [comment]
+1

Having the same issue here trying to get an empty ec2 hint going.

**Comment by tas50** [comment]
Should be fixed with the merge of #22.  Let me know if that doesn't solve it for you.  I'll try to get a release out soon.
