### ISSUE TITLE
ChefSpec Matcher Deprecation

### ISSUE THREAD

**Issue by rmoriz** [chef-cookbooks/ohai#28]
```[DEPRECATION] `ChefSpec::Runner.define_runner_method' is deprecated. It is being used in the ohai_hint resource matcher. Please use `ChefSpec.define_matcher' instead. ```

https://github.com/chef-cookbooks/ohai/blob/master/libraries/matchers.rb

see https://github.com/sethvargo/chefspec/commit/18b2e6a0dd320cc1c41acbd9b9eb24481a70fc66

**Comment by Chili-Man** [comment]
I'm getting a lot of these warnings as well

**Comment by rmoriz** [comment]
https://github.com/crap-cookbooks/ohai/commit/a6ca56d7f6da7b8ecccae59f699c677d02a087e0

**Comment by tas50** [comment]
This should be fixed in 2.0.4

**Comment by phs** [comment]
Link to fixing commit?

**Comment by tas50** [comment]
https://github.com/chef-cookbooks/ohai/commit/8df71057bd78bfaa462d1c58550644da8decc803
