### ISSUE TITLE
receiving multiple warnings

### ISSUE THREAD

**Issue by chazzly** [chef-cookbooks/ohai#29]
Running Rspec/ ChefSpec, i'm getting spammed with the following Warning for each example"

<code>WARN: Ohai::Config[:plugin_path] is set. Ohai::Config[:plugin_path] is deprecated and will be removed in future releases of ohai. Use ohai.plugin_path in your configuration file to configure :plugin_path for ohai.</code>

This happens with any cookbook, which depends on the ohai cookbook (directly or down the chain), so it does not 'appear' to be specific to my code.

chefdk- 0.10
ohai cookbook -  2.0.4
Oracle Linux 6.5
chefspec - 4.4.0

**Comment by bleything** [comment]
I'm also experiencing this. It was a mild annoyance right up until the noise of these warnings for every.single.example caused me to miss legitimate warnings and waste a bunch of time :cold_sweat: 

I just played around a bit and discovered that changing `Ohai::Config[:plugin_path]` to `Ohai.config[:plugin_path]` in `recipes/default.rb` makes the warnings go away. I'm not sure if that will have repercussions for older versions of ohai or chef, but it definitely fixes it for whatever versions are in the current chefdk.

**Comment by jorhett** [comment]
I would disagree that this is resolved as it's only fixed for a subset of people using this cookbook.

**Comment by chazzly** [comment]
If you're talking about this change breaking under Chef 11, that looks to be being tracked in #38

**Comment by jorhett** [comment]
@chazzly um, #38 says "Fixed in 4.0" and the 4.0 release says in big letters that it only works in Chef 12 and that we must stay with v3... which has the problem listed above for all pre-Chef12 versions.
