### ISSUE TITLE
ohai[reload] executing during every converge

### ISSUE THREAD

**Issue by jsmickey** [chef-cookbooks/ohai#31]
I have a wrapper cookbook using https://github.com/chef-cookbooks/aws with:
  include_recipe 'aws::ec2_hints'

The recipe runs and works as expected.  But the following is being run every time
```
ohai 'reload' do
  action :nothing
end.run_action(:reload)
```
Chef log shows this:
```
* ohai[reload] action reload/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.5.0/lib/ohai/plugins/solaris2/network.rb:57: warning: already initialized constant ETHERNET_ENCAPS
       /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.5.0/lib/ohai/plugins/solaris2/network.rb:57: warning: previous definition of ETHERNET_ENCAPS was here
       
           - re-run ohai and merge results into node attributes
```
I get the same output on every converge.  The OS is Ubuntu 14.04.  I'm not sure about the references to solaris2.  Is anybody else seeing this output?  Any ideas on how to fix this?

**Comment by TheSerapher** [comment]
We are also seeing this on every converge. It's not an issue by itself other than having to wait for OHAI to re-run with all plugins enabled. I'd rather find a way to skip this unless changes have been done to any plugin installed but it's not a huge issue.

**Comment by TheSerapher** [comment]
I think I figured out what causes the restart:

https://github.com/chef-cookbooks/ohai/blob/master/attributes/default.rb#L26

This sets the plugin path for installable plugins. When checking the `Ohai::Config[:plugin_path]` option it doesn't include this path and hence causes the forced reload here:

https://github.com/chef-cookbooks/ohai/blob/master/recipes/default.rb#L23-L26

I got around this by changing the default attribute in my wrapper cookbook to only point to `/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.10.0/lib/ohai/plugins`. Of course this would mean all plugins have to be reinstalled when upgrading Chef.

**Comment by tas50** [comment]
I'm working on a complete rewrite of this cookbook.  It includes a resource ohai_plugin for installing the plugins.  That resource compares the current ohai plugin_path with the desired directory where the plugin is being installed.  If the desired directory isn't in the path it adds it and reloads ohai.  It will also issue a warning that unless the desired directory is added to the plugin path via the client.rb config you'll get a reload on every chef run.  Since we can't actually modify the config via this recipe it's best that we just explain why this reload occurs so people can fix it via the chef-client cookbook.

**Comment by tas50** [comment]
The 4.0 release is out and it changes how the reloads happen and includes additional logging.  With the new provider the user can now provide a path for their custom plugins or the cookbook will stick them in /etc/chef/ohai/plugins.  The reload will occur if that directory isn't in the current plugin path. If the reload occur the cookbook throws a warning that the reload will happen on every chef run unless the new directory is added to the plugin path. The warning includes a link to the config documentation.
