### ISSUE TITLE
disabled_plugins causes WARN messages.

### ISSUE THREAD

**Issue by docwhat** [chef-cookbooks/ohai#32]
Setting:

```
default_attributes(
  ohai: {
    disabled_plugins: %w(
      :Cloud
      :Azure
      :Cloudstack
      :CloudV2
      :EC2
      :Eucalyptus
      :GCE
      :Joyent
      :Linode
      :Rackspace
    )
  }
)
```

Causes Chef to spew this WARNing:

```
[2016-03-02T15:48:59-05:00] WARN: Ohai::Config[:disabled_plugins] is set. Ohai::Config[:disabled_plugins] is deprecated and will be removed in future releases of ohai. Use ohai.d
isabled_plugins in your configuration file to configure :disabled_plugins for ohai.
```

This is on Chef v12.5.1 to v12.7.2

**Comment by tas50** [comment]
Which version of the cookbook are you running? I thought we resolved this with the last release

**Comment by hwhopemaIBM** [comment]
We are running Ohai 2.1.0

**Comment by docwhat** [comment]
We're running ohai 2.1.0, which is the latest in supermarket at the moment.

**Comment by tas50** [comment]
@hwhopemaIBM / @docwhat I thought I fixed all the warning issues, but apparently not. Thanks for the report I'll track down what's going on here.

**Comment by tas50** [comment]
So the plugins are actually disabled via the chef-client cookbook and I confirmed that we're templating out the new format there:

ohai.disabled_plugins = ["Mdadm"]

If you upgrade to the latest chef-client cookbook this issue should go away.

**Comment by docwhat** [comment]
I'll delete all the older ohai cookbooks and see if any nodes fail due to dependencies or such.

**Comment by docwhat** [comment]
Huh... okay, 2.10 is working correctly now that I removed the older cookbooks. I wonder if it was pulling older versions or something else.  Thanks for the help!

**Comment by docwhat** [comment]
Ah-hah! :mag:

I found the problem. It wasn't the `ohai` cookbook, but rather it was `chef-client` version 4.3.2.  I upgraded to 4.3.3 and life became better and WARN free!

Sorry for posting this on the wrong cookbook.  Hopefully it'll help others, though.
