### ISSUE TITLE
undefined method `config' for Ohai:Module

### ISSUE THREAD

**Issue by egonbraun** [chef-cookbooks/ohai#38]
### Cookbook version
3.0.1

### Chef-client version
11.10.4

### Platform Details
AWS - Ubuntu 14.04 Trusty

### Scenario:
I am trying to deploy one of my apps which uses this cookbook as a dependency

### Steps to Reproduce:
This is happening during the cookbook compile time.

### Expected Result:
Execution of the cookbook build process to continue

### Actual Result:
================================================================================
Recipe Compile Error in /var/lib/aws/opsworks/cache.stage2/cookbooks/ohai/attributes/default.rb
================================================================================
 
NoMethodError
-------------
undefined method `config' for Ohai:Module
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/ohai/attributes/default.rb:30:in `from_file'
 
 
Relevant File Content:
----------------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/ohai/attributes/default.rb:
 
23:                                     "#{ENV['systemdrive']}/chef/ohai_plugins"
24:                                   else
25:                                     '/etc/chef/ohai_plugins'
26:                                   end
27:  
28:  # The list of plugins and their respective file locations
29:  default['ohai']['plugins']['ohai'] = 'plugins'
30>> default['ohai']['hints_path'] = Ohai.config[:hints_path].first
31:

**Comment by tas50** [comment]
This is fixed with the 4.0 release, which properly supports both Ohai 8.6.0 config format and the previous format.
