### ISSUE TITLE
allow to specify a cookbook for plugin template/cookbook-file resources

### ISSUE THREAD

**Issue by rmoriz** [chef-cookbooks/ohai#44]
Use case:

- You've a generic nginx cookbook that uses this cookbook to render out a custom ohai plugin
- In a special case you'll wrap this cookbook and want to provide a different template for that plugin (or hint).

Solution:
- allow to set a `cookbook` value for both resources in https://github.com/chef-cookbooks/ohai/blob/a2e01d65eb898632bb2b1a9bf29a4bf8fba3db6a/resources/plugin.rb#L78-L89

**Comment by tas50** [comment]
That's totally doable and would be really helpful. I'll keep it in mind the next time I have time for this cookbook.

**Comment by tas50** [comment]
Fix here https://github.com/chef-cookbooks/ohai/commit/10ce34f59de6236b8c11157de0bf6d8269b15480
