### ISSUE TITLE
error executing ohai_plugin

### ISSUE THREAD

**Issue by kmanohar1** [chef-cookbooks/ohai#51]
I am using the latest ohai cookbook. Here is my code
ohai_plugin 'My Ohai Plugin' do
  name 's1'
  path '/var/chefworkstation/ohai_plugins'
end

I am not sure why I am getting the following error:
 Error executing action `create` on resource 'cookbook_file[/var/chefworkstation/ohai_plugins/s1.rb]'

**Comment by kmanohar1** [comment]
I figured out the issue, it is working now. Thx.

One thing that I noticed is that while developing a custom plugin, we do need ohai to reload evrytime chef-client runs.

**Comment by tas50** [comment]
If you don't specify that plugin location in your Chef client.rb the ohai plugin resource has to do some fancy work to make sure the path you're specifying is added and part of that is to reload ohai to load in your plugin. If you add it to the client.rb config you can avoid that reload.
