### ISSUE TITLE
NameError: No resource, method, or local variable named desired_plugin_path

### ISSUE THREAD

**Issue by 8la** [chef-cookbooks/ohai#57]
### Cookbook version
5.0.0

### Chef-client version
12.5.3

### Platform Details
centos7

### Scenario:
configure a custom plugin using cookbook file and custom ohai_plugins path

### Steps to Reproduce:
use ohai_plugin  resource on a company cookbook with your plugin file as a cookbook file
```ruby
ohai_plugin "Physicalmem" do
  name "pmemory"
  path node['ohai']['plugin_path']
  source_file 'plugins/ohai_memmory.rb'
end
```

Plugin code: 

```ruby
Ohai.plugin(:PhysicalMemory) do
  provides 'memory/physical'

  collect_data(:linux) do
    memory Mash.new unless memory

    begin
      so = shell_out('dmidecode -t memory')
      size_in_mb = so.stdout.lines.grep(/^\tSize: ([0-9]*)/).map(&:split)[0].collect(&:to_i).map(&:to_i).reduce(&:+)
      size = "#{size_in_mb * 1024}kB"
    rescue
      size = '0kB'
    end
    memory['physical'] = size
  end
end
```
### Expected Result:
Plugin on /etc/chef/ohai_plugins and working

### Actual Result:
`ohai_plugin[Physicalmem] (stic_base::_ohai_memory line 32) had an error: NameError: No resource, method, or local variable named `desired_plugin_path' for `LWRP resource ohai_plugin from cookbook ohai action provider "Physicalmem"'`

The function is defined on /tmp/kitchen/cache/cookbooks/ohai/resources/plugin.rb:12 but chef-client complains about not being defined.

**Comment by 8la** [comment]
Error disappeared with Chef 12.7

May be Readme.md should be changed: https://github.com/chef-cookbooks/ohai#chef

**Comment by tas50** [comment]
5.0.1 has been released with a dep on 12.7. I'm not sure what changed in 12.7 that fixed it but I'll trust you that this is the fix

**Comment by bitmonk** [comment]
This problem occurs for us with Chef 12.18.31, and does not occur on 12.7.2.

**Comment by iamsureshraju** [comment]
We have freezed the Chef Client to 12.6. Could you please suggest an alternate fix or workaround to this case.

**Comment by tas50** [comment]
If you can't upgrade Chef Client you'll need to use the 4.X branch. I'd highly recommend upgrading chef-client though as we won't be supporting 12.5 in community cookbooks going forward. 12.5 came out at the end of 2015 and is outside our cookbooks support window at this point.
