### ISSUE TITLE
v5.0.1 not on Supermarket

### ISSUE THREAD

**Issue by hrak** [chef-cookbooks/ohai#61]
### Cookbook version
v5.0.1

### Chef-client version
12.10.24

### Platform Details
Ubuntu 14.04

Not super important since the change from 5.0.0 to 5.0.1 is not that big, but 5.0.1 does not seem to have made it to Supermarket (no v5.0.1 tag either).

**Comment by tas50** [comment]
Looks like my push failed. I pushed again
