### ISSUE TITLE
Ohai and plugin paths with subdirectories has validation issues

### ISSUE THREAD

**Issue by jaymzh** [chef-cookbooks/ohai#72]
### Cookbook version
5.2.2

### Chef-client version
13.9.1

### Platform Details
RHEL 7

### Scenario:
Custom plugins

### Steps to Reproduce:
To use subdirectories in your ohai plugins directory you cannot do the intuitive:

```
# Plugin dir is '/etc/chef/ohai_plugins'
ohai_plugin 'filesystem2' do
  source_file 'plugins/bsd/filesystem2.rb'
  plugin_path '/etc/chef/ohai_plugins/bsd'
end
```

Because you will get warnings that `/etc/chef/ohai_plugins/bsd` isn't in your plugin path (but if course it is, if `/etc/chef/ohai_plugins` is then all subdirectories are too.

Now you CAN make this work with:

```
ohai_plugin 'bsd/filesystem2' do
  source_file 'plugins/bsd/filesystem2.rb'
  plugin_path '/etc/chef/ohai_plugins'
end
```

But this seems less-good.  and more repetitive. At the very least the validation https://github.com/chef-cookbooks/ohai/blob/master/libraries/plugin_helpers.rb#L50 should probably be:

```
::Ohai::Config.ohai['plugin_path'].map { |x| normalize_path(x) }.any? do |d|
  desired_dir.start_with?(d)
end
```

But I suspect that's not the only change that would be required.

### Expected Result:
The first one to work

### Actual Result:
The first one yells at you and causes reloads of Ohai on every run.

**Comment by NaomiReeves** [comment]
In addition to this, if you happen to pass in `/etc/chef/ohai_plugins/` (with the trailing slash) to the `plugin_path` property of the `ohai_plugin` resource, Ohai will return the `plugin_path_warning` and reload Ohai on every run.

**Comment by tas50** [comment]
I think we can pretty easily chomp off the trailing slash on the provided plugin path to fix @NaomiReeves's issue. I think the map to check for the start of the dir would work nicely for the nested dir issues. I'll get a spec added for that use case as well. It just wasn't something I considered when I tossed this together.

**Comment by tas50** [comment]
Give 5.2.3 a try and open this back up if it's still an issue.

**Comment by NaomiReeves** [comment]
@tas50 it worked 👍 Thanks!
